package dao;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import org.h2.tools.Server;

/**
 * Utilidad simple para obtener conexiones a H2
 * y crear el esquema mínimo.
 *
 * Configuración mediante variables de entorno:
 * - `DB_URL` (recomendada): URL JDBC del servicio H2 (ejemplo: `jdbc:h2:tcp://<host>:<port>/~/votacion;MODE=PostgreSQL`).
 *   Si no se proporciona, la aplicación usa una base en memoria para permitir ejecución local/CI.
 * - `DB_USER` y `DB_PASS`: credenciales para el servicio H2 (por defecto `sa` y contraseña vacía).
 */
public final class Database {
    /**
     * Si es true, la aplicación funciona en modo "in-memory" y evita usar la base de datos.
     * Se puede forzar por variable de entorno `DB_IN_MEMORY=true`.
     * Por defecto está deshabilitado (usar base de datos real).
     */
    public static final boolean IN_MEMORY;
    /**
     * Default URL: if DB_URL not provided, prefer an H2 file-based DB inside the project
     * so the application can run without an external DB. H2 runs in PostgreSQL compatibility
     * mode to improve SQL compatibility.
     */
    // Preferir la URL en la nube mediante la variable de entorno.
    // Si no está definida, usar una base H2 en archivo dentro del proyecto
    // para asegurar persistencia entre reinicios/contenedores cuando se monte
    // el volumen apropiadamente.
    private static final String URL = System.getenv().getOrDefault("DB_URL", "jdbc:h2:./data/mibase;MODE=PostgreSQL");
    // Credenciales por defecto para H2: usuario `sa` y contraseña vacía.
    private static final String USER = System.getenv().getOrDefault("DB_USER", "sa");
    private static final String PASS = System.getenv().getOrDefault("DB_PASS", "");
    

    static {
        String inMem = System.getenv("DB_IN_MEMORY");
        IN_MEMORY = inMem == null ? false : Boolean.parseBoolean(inMem);
        try {
            Class.forName("org.h2.Driver");
        } catch (ClassNotFoundException e) {
            // Driver no disponible en classpath; la dependencia H2 en `pom.xml` debería proveerlo.
        }
    }

    private Database() {}

    // H2 web console server (optional)
    private static Server webServer = null;

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASS);
    }

    /** Crea tablas básicas si no existen. */
    public static void initSchema() throws SQLException {
        // Si la URL apunta a un archivo local relativo (p.ej. jdbc:h2:./data/mibase...),
        // asegurarnos de que la carpeta existe para que H2 pueda crear los archivos.
        try {
            if (URL.startsWith("jdbc:h2:./") || URL.startsWith("jdbc:h2:file:") || URL.startsWith("jdbc:h2:file:./")) {
                String path = URL.substring("jdbc:h2:".length());
                int semi = path.indexOf(';');
                if (semi != -1) path = path.substring(0, semi);
                if (path.startsWith("file:")) path = path.substring("file:".length());
                File db = new File(path);
                File dir = db.getParentFile();
                if (dir != null && !dir.exists()) {
                    dir.mkdirs();
                }
            }
        } catch (Exception ignore) {
            // No fallamos aquí; si no se puede crear la carpeta, H2 lanzará la excepción
        }

        try (Connection c = getConnection(); Statement s = c.createStatement()) {
            // DDL compatible con H2 (válido para servidor remoto o archivo local).
            s.executeUpdate("CREATE TABLE IF NOT EXISTS ciudadanos (curp VARCHAR PRIMARY KEY, nombre VARCHAR, distrito VARCHAR);");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS dependientes (curp_dependiente VARCHAR PRIMARY KEY, nombre VARCHAR, curp_tutor VARCHAR, distrito VARCHAR);");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS votos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, curp VARCHAR, distrito VARCHAR, proyecto VARCHAR, corredor VARCHAR, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS proyectos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre VARCHAR NOT NULL, distrito VARCHAR, descripcion VARCHAR, activo BOOLEAN DEFAULT TRUE, UNIQUE(nombre, distrito));");
        }

        // Arrancar la consola web H2 si está activada por variable de entorno
        try {
            String enable = System.getenv("H2_ENABLE_WEB");
            if (enable != null && enable.equalsIgnoreCase("true")) {
                String portStr = System.getenv().getOrDefault("PORT", "8082");
                int port = 8082;
                try { port = Integer.parseInt(portStr); } catch (NumberFormatException ignore) {}
                try {
                    webServer = Server.createWebServer("-webPort", String.valueOf(port), "-webAllowOthers").start();
                    System.out.println("H2 console running at: " + webServer.getURL());
                } catch (SQLException se) {
                    System.err.println("No se pudo iniciar H2 web console: " + se.getMessage());
                }
            }
        } catch (Throwable t) {
            // No detener la app si falla el intento de iniciar la consola
            System.err.println("Warning: no se pudo evaluar H2_ENABLE_WEB: " + t.getMessage());
        }
    }
}
