package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Utilidad simple para obtener conexiones a H2
 * y crear el esquema mínimo.
 *
 * Configuración mediante variables de entorno:
 * - `DB_URL` (recomendada): URL JDBC del servicio H2 (ejemplo: `jdbc:h2:tcp://<host>:<port>/~/votacion;MODE=PostgreSQL`).
 *   Si no se proporciona, la aplicación usa una base en memoria para permitir ejecución local/CI.
 * - `DB_USER` y `DB_PASS`: credenciales para el servicio H2 (por defecto `sa` y contraseña vacía).
 */
public final class Database {
    /**
     * Si es true, la aplicación funciona en modo "in-memory" y evita usar la base de datos.
     * Se puede forzar por variable de entorno `DB_IN_MEMORY=true`.
     * Por defecto está deshabilitado (usar base de datos real).
     */
    public static final boolean IN_MEMORY;
    /**
     * Default URL: if DB_URL not provided, prefer an H2 file-based DB inside the project
     * so the application can run without an external DB. H2 runs in PostgreSQL compatibility
     * mode to improve SQL compatibility.
     */
    // Preferir la URL en la nube mediante la variable de entorno.
    // Si no está definida, usar una base H2 en memoria para ejecutar localmente o en CI.
    private static final String URL = System.getenv().getOrDefault("DB_URL", "jdbc:h2:mem:votacion;DB_CLOSE_DELAY=-1;MODE=PostgreSQL");
    // Credenciales por defecto para H2: usuario `sa` y contraseña vacía.
    private static final String USER = System.getenv().getOrDefault("DB_USER", "sa");
    private static final String PASS = System.getenv().getOrDefault("DB_PASS", "");
    

    static {
        String inMem = System.getenv("DB_IN_MEMORY");
        IN_MEMORY = inMem == null ? false : Boolean.parseBoolean(inMem);
        try {
            Class.forName("org.h2.Driver");
        } catch (ClassNotFoundException e) {
            // Driver no disponible en classpath; la dependencia H2 en `pom.xml` debería proveerlo.
        }
    }

    private Database() {}

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASS);
    }

    /** Crea tablas básicas si no existen. */
    public static void initSchema() throws SQLException {
        try (Connection c = getConnection(); Statement s = c.createStatement()) {
            // DDL compatible con H2 (válido para servidor remoto o memoria).
            s.executeUpdate("CREATE TABLE IF NOT EXISTS ciudadanos (curp VARCHAR PRIMARY KEY, nombre VARCHAR, distrito VARCHAR);");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS dependientes (curp_dependiente VARCHAR PRIMARY KEY, nombre VARCHAR, curp_tutor VARCHAR, distrito VARCHAR);");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS votos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, curp VARCHAR, distrito VARCHAR, proyecto VARCHAR, corredor VARCHAR, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS proyectos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre VARCHAR NOT NULL, distrito VARCHAR, descripcion VARCHAR, activo BOOLEAN DEFAULT TRUE, UNIQUE(nombre, distrito));");
        }
    }
}
